export const BASE_URL = 'http://192.168.1.5:5000';
export const TEAM_OFFICE_BASE_URL = '/api/etimeoffice';
export const TEAM_OFFICE_AUTH_TOKEN = 'c3VwcG9ydDpzdXBwb3J0OnN1cHBvcnRAMTp0cnVl';

export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/api/login`,
  REGISTER: `${BASE_URL}/api/register`,
  PROFILE: `${BASE_URL}/api/profile`,
  PROFILE_UPDATE: `${BASE_URL}/api/profile/update`,
  UPDATE_PROFILE: `${BASE_URL}/api/profile/update`,
  PROFILE_ABOUT: `${BASE_URL}/api/profile/about`,
  PROFILE_MANAGER: `${BASE_URL}/api/profile/manager`,
  PROFILE_UPLOAD_DOC: `${BASE_URL}/api/profile/upload-doc`,
  PROFILE_UPLOAD_DOCUMENT: `${BASE_URL}/api/upload-document`,
  PROFILE_UPLOAD_DOCUMENT_ALT: `${BASE_URL}/api/profile/upload-document`,
  PROFILE_UPLOAD_DIRECT: `${BASE_URL}/api/profile/upload-direct`,
  MANAGER_UPLOAD_IMAGE: `${BASE_URL}/api/managers/upload-image`,
  EMPLOYEE_PROFILE_GET: (id) => `${BASE_URL}/api/employee-profile/${id}`,
  EMPLOYEE_PROFILE_UPDATE: `${BASE_URL}/api/employee-profile/update`,
  EMPLOYEE_PROFILE_DELETE: (id) => `${BASE_URL}/api/employee-profile/${id}`,
  THREADS: `${BASE_URL}/api/threads`,
  THREAD_REACT: (id) => `${BASE_URL}/api/threads/${id}/react`,
  THREAD_REACTORS: (id, type) => `${BASE_URL}/api/threads/${id}/reactors${type ? `?type=${encodeURIComponent(type)}` : ''}`,
  THREAD_BADGE: (id) => `${BASE_URL}/api/threads/${id}/badge`,
  THREAD_COMMENT: (id) => `${BASE_URL}/api/threads/${id}/comment`,
  THREAD_COMMENTS: (id) => `${BASE_URL}/api/threads/${id}/comments`,
  THREAD_UPDATE: (id) => `${BASE_URL}/api/threads/${id}`,
  THREAD_DELETE: (id) => `${BASE_URL}/api/threads/${id}`,
  THREAD_USER: (userId) => `${BASE_URL}/api/threads/user/${userId}`,
  COMMENT_DELETE: (threadId, commentId) => `${BASE_URL}/api/threads/${threadId}/comments/${commentId}`,
  COMMENT_UPDATE: (threadId, commentId) => `${BASE_URL}/api/threads/${threadId}/comments/${commentId}`,
  TASKS: `${BASE_URL}/api/tasks`,
  TASK_UPDATES: `${BASE_URL}/api/task-updates`,
  TEAMS: `${BASE_URL}/api/teams`,
  EMPLOYEES: `${BASE_URL}/api/employees`,
  HOLIDAYS: `${BASE_URL}/api/holidays`,
  COURSES: `${BASE_URL}/api/courses`,
  COURSES_DELETE: (id) => `${BASE_URL}/api/courses/${id}`,
  SUGGESTIONS: `${BASE_URL}/api/suggestions`,
  ASSIGN_TASK: `${BASE_URL}/api/assign-task`,
  ASSIGN_TASK_REVIEW: `${BASE_URL}/api/assign-task/review`,
  ASSIGNED_TASKS_GET: `${BASE_URL}/api/tasks/all-assigned`,
  USER_TASKS_GET: `${BASE_URL}/api/tasks/assigned`,
  MANAGER_TASKS_GET: `${BASE_URL}/api/tasks/manager`,
  SPRINT_UPDATES_GET: `${BASE_URL}/api/sprint-updates`,
  SUBORDINATES_GET: `${BASE_URL}/api/subordinates`,
  ALERTS: `${BASE_URL}/api/notifications`,
  USERS: `${BASE_URL}/api/users`,
  BIRTHDAYS: `${BASE_URL}/api/birthdays`,
  SUPPORT_TICKETS: `${BASE_URL}/api/support-tickets`,
  PROJECT_SPRINTS: `${BASE_URL}/api/project-sprints`,
  SPRINTS_STATUS: `${BASE_URL}/api/sprints-status`,
  NEW_JOINEES: `${BASE_URL}/api/new-joinees`,
  NEW_JOINEE_UPDATE: (id) => `${BASE_URL}/api/new-joinees/${id}`,
  NEW_JOINEE_COURSES: `${BASE_URL}/api/newjoinee_courses`,
  PROFILE_UPLOAD_IMAGE: `${BASE_URL}/api/profile/upload-image`,
  TASKS_ASSIGNED: (uid) => `${BASE_URL}/api/tasks/assigned/${uid}`,
  NOTIFICATIONS_BY_USER: (uid) => `${BASE_URL}/api/notifications/${uid}`,
  MASTER_TASKS_GET: `${BASE_URL}/api/tasks`,
  ATTENDANCE_LOGS_GET: `${BASE_URL}/api/attendance_logs`,
  ATTENDANCE_PUNCH_UPDATE: `${BASE_URL}/api/attendance/update-punch-time`,
  LEAVES_GET: `${BASE_URL}/api/leaves/all`,
  LEAVE_BALANCE: (userId) => `${BASE_URL}/api/leaves/balance/${userId}`,
  LEAVE_REQUEST: `${BASE_URL}/api/leaves/request`,
  UPDATE_LEAVE_STATUS: (id) => `${BASE_URL}/api/leaves/${id}/status`,
  MY_LEAVES_GET: (userId) => `${BASE_URL}/api/leaves/my?userId=${userId}`,
  ALL_LEAVES: `${BASE_URL}/api/leaves/all`,
  LEAVES_UPDATE: `${BASE_URL}/api/admin/leaves/update`,
  LEAVE_STATS_MY: `${BASE_URL}/api/leave-stats`,
  ADMIN_LEAVE_STATS: `${BASE_URL}/api/admin/leaves/stats`,
  ADMIN_LEAVE_STATS_UPDATE: `${BASE_URL}/api/admin/leaves/stats`,
  SERVICE_CERTIFICATES_GET: `${BASE_URL}/api/service_certificate_requests`,
  SERVICE_CERTIFICATES_ALT: `${BASE_URL}/api/admin/service-certificates`,
  SERVICE_CERTIFICATE_UPDATE: (id) => `${BASE_URL}/api/service_certificate_requests/${id}`,
  RESIGNATIONS_GET: `${BASE_URL}/api/admin/resignations`,
  RESIGNATION_UPDATE: (id) => `${BASE_URL}/api/admin/resignations/${id}`,
  RESIGNATION_REQUEST: `${BASE_URL}/api/resignations`,
  SERVICE_CERTIFICATE_REQUEST: `${BASE_URL}/api/service_certificate_requests`,
  PAYSLIPS_GET: `${BASE_URL}/api/payslips`,
  REWARDS_HISTORY: `${BASE_URL}/api/admin/rewards/history`,
  USER_REWARDS: (id) => `${BASE_URL}/api/rewards/user/${id}`,
  REWARDS: `${BASE_URL}/api/rewards`,
  REWARD_EDIT: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_DELETE: (id) => `${BASE_URL}/api/rewards/${id}`,
  REWARD_CATEGORIES: `${BASE_URL}/api/rewards/categories`,
  REWARDS_GIVE: `${BASE_URL}/api/rewards`,
  LEADERBOARD_ALL: `${BASE_URL}/api/employees/leaderboard/all`,
  ASSETS: `${BASE_URL}/api/assets`,
  ASSET_UPDATE: (id) => `${BASE_URL}/api/assets/${id}`,
  ASSET_GET: `${BASE_URL}/api/assets`,
  HIERARCHY_REALIGN: `${BASE_URL}/api/hierarchy/realign`,
  INTERNS: `${BASE_URL}/api/interns`,
  INTERN_UPDATE: (id) => `${BASE_URL}/api/interns/${id}`,
  INTERN_PROMOTE: (id) => `${BASE_URL}/api/interns/promote/${id}`,
  INTERN_DELETE: (id) => `${BASE_URL}/api/interns/${id}`,
  QUIZ_SUBMIT_TOTAL: `${BASE_URL}/api/quizzes/submit-session`,
  QUIZ_SUBMIT_ANSWER: `${BASE_URL}/api/fun-quizzes/submit-answer`,
  SUGGESTIONS_ADMIN: `${BASE_URL}/api/admin/suggestions`,
  SERVICE_CERTIFICATE_MY: `${BASE_URL}/api/service_certificate_requests/my`,
  SERVICE_CERTIFICATE_SINGLE: (id) => `${BASE_URL}/api/service_certificate_requests/${id}`,
  TEAM_RENAME: `${BASE_URL}/api/admin/teams/rename`,
  TEAM_CREATE: `${BASE_URL}/api/admin/teams/create`,
  PASSWORD_CHANGE: `${BASE_URL}/api/password/change-password`,
  PASSWORD_RESET: `${BASE_URL}/api/password/reset-with-otp`,
  UNBLOCK_ALL_JOINEES: `${BASE_URL}/api/admin/new-joinees/unblock-all`,
  UNBLOCK_ALL_JOINEES_ALT: `${BASE_URL}/api/new-joinees/unblock-all`,
  NEW_JOINEE_UNBLOCK: (id) => `${BASE_URL}/api/new-joinees/${id}/unblock`,
  NEW_JOINEE_UNBLOCK_ADMIN: (id) => `${BASE_URL}/api/admin/new-joinees/${id}/unblock`,
  QUIZ_LEADERBOARD: `${BASE_URL}/api/fun-quizzes/leaderboard`,
  ONBOARDING_REMINDERS: `${BASE_URL}/api/admin/onboarding/reminders`,
  ONBOARDING_PROMOTE: `${BASE_URL}/api/admin/onboarding/promote`,
};

